modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/ThisTestUser/FarLandsModV2/issues"
[[mods]]
modId="farlandsmod"
version="${file.jarVersion}"
displayName="Far Lands Mod"
authors="ThisTestUser"
description='''
Restore the far lands!
'''

[[dependencies.farlandsmod]]
modId="forge"
mandatory=true
versionRange="[26,)"
ordering="NONE"
side="BOTH"

[[dependencies.farlandsmod]]
modId="minecraft"
mandatory=true
versionRange="[1.14.2,)"
ordering="NONE"
side="BOTH"